### ISSUE TITLE
JSON format for AIS encoding

### ISSUE THREAD

**Issue by bitconbyte** [GlobalFishingWatch/ais-tools#44]
What is the JSON format for the encoder ? Is there any example?

**Comment by pwoods25443** [comment]
Sorry - I didn't see this until now. This has been a solo project for a long time.

The JSON for the encoder is identical to the JSON returned by the decoder, which is the JSON schema that is used by [libais](https://github.com/schwehr/libais).   Note however that only some message type can be encoded.  The messages that pass through to `libais` to be decoded do not have encoders.   Right now that is just message types 8, 18, 19, 24, 25.    Each time we need a decoder that is different from `libais` we add another message type.

To get sample JSON for encoding, the best thing to do is run a few messages through decode and capture the output.
