### ISSUE TITLE
False precision in lat/lon decoding

### ISSUE THREAD

**Issue by pwoods25443** [GlobalFishingWatch/ais-tools#9]
## Description

Because Lat/Lon are encoded in minutes*10000 and we output lat/lon in decimal degrees, we sometimes have long repeating decimal values that can suggest a greater precision than is actually present.

For example, an encoded lat value of `25339016` is `25339016 / 10000 = 2533.9016` minutes which is `2533.9016 / 60 = 42.23169333333333` degrees

We really only have slightly less than 6 digits of precision after the decimal, so it makes sense to round this off when producing an output

## Steps to reproduce
```console
$ echo '!AIVDM,1,1,,A,B3EkLKP0BWmtImV2a8RMMuP10D00,0*39' | ais-tools decode | jq .y
42.23169333333333
```

## Proposed Solution
Round to 6 digits in `transcode.LatLonTranscoder.decode_value()`

```python
class LatLonTranscoder(FieldTranscoder):
...
    def decode_value(self, bits):
        return round(bits.int / 600000.0, 6)
```

**Comment by pwoods25443** [comment]
The same thing is true for `cog` and `sog`.   Propose to round them to 1 digit after the decimal

**Comment by pwoods25443** [comment]
ok but the cog/sog thing is not an issue for thee python decoder - dividing a unit by 10.0 does not generate extra decimal places.   The only problem is when you compare the results to libais which has repeating decimals for cog and sog

**Comment by WSP001** [comment]
My Last function written to include  "beginning, repeating, and or terminating cog and sog decimal rewind value(s) commit
